steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - dataDelivery
  - --source=CloudFunction
  - --region=$_REGION 
  - --runtime=python37
  - --trigger-event=google.pubsub.topic.publish
  - --trigger-resource=$_DATADELIVERY_PUBSUB
  - --set-env-vars=pat_token=$_PAT_TOKEN,var_group_name=$_VAR_GROUP_NAME,env_name=$_ENV_NAME
  - --timeout=540s
