parameters:
  - name : VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger:
- none

variables:
 - group: ${{ parameters.VarGroup }}
 - name: ServerParkName
   value: gusty
 - name: SurveyType
   value: OPN
 - name: PackageExtension
   value: zip

stages:
 - stage: DataDelivery
   displayName: DataDelivery
   variables:
      ENV_RESTAPI_URL : http://localhost:90
   jobs:
     - deployment: DeliveryData
       environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapi
       strategy:
        runOnce:
          deploy: 
           steps:
             - checkout: self
             
             - task: DownloadSecureFile@1
               displayName: 'Download GCP Key'
               name: gcpkey
               inputs:
                  secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'

             - task: PowerShell@2
               displayName: Download test instrument
               inputs:
                  targetType: 'inline'
                  script: |
                    Write-Host "Login to GCP"
                        gcloud auth activate-service-account $env:ENV_SHARED_SERVICE_ACCOUNT --key-file=$(gcpkey.secureFilePath)
                        
                        Write-Host "Downloading instrument"
                        gsutil cp gs://$env:ENV_SHARED_BUCKET/SpssPackage.zip C:\blaise\SpssPackage.zip

                        Write-Host "GCP Login with compute service account"
                        gcloud auth login $env:ENV_VM_SERVICEACCOUNT

             - task: PowerShell@2
               displayName: Deliver Instruments
               inputs:
                 filePath: '$(Agent.BuildDirectory)/s/scripts/DeliverInstruments.ps1'
