---
parameters:
  - name: VarGroup
    displayName: Variable group
    type: string
    default: '' # Added default value for validation
  - name: Environment
    displayName: Environment to use
    type: string
    default: '' # Added default value for validation
  - name: SurveyType
    displayName: Survey type
    type: string
    default: '' # Added default value for validation
  - name: Questionnaires
    displayName: Questionnaires separated by commas
    default: ' ' # Space required or it breaks Azure DevOps !?

trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - name: SurveyType
    value: ${{parameters.SurveyType}}
  - name: Questionnaires
    value: ${{parameters.Questionnaires}}
  - name: ProcessingPath
    value: c:\blaise\temp\datadelivery\${{parameters.SurveyType}}
stages:
  - stage: DataDelivery
    displayName: Data delivery
    jobs:
      - deployment: DataDelivery
        timeoutInMinutes: 0
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: data-delivery
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: /templates/set_vm_default_sa.yml
                  parameters:
                    DefaultServiceAccount: $(ENV_VM_SERVICEACCOUNT)
                - task: PowerShell@2
                  displayName: Register Blaise
                  inputs:
                    filePath: $(Agent.BuildDirectory)/s/scripts/RegisterBlaise.ps1
                    arguments: '-BLAISE_LICENSE_KEY $(ENV_BLAISE_LICENSE_KEY) -BLAISE_ACTIVATION_CODE $(ENV_BLAISE_ACTIVATION_CODE)'
                    pwsh: true
                - template: /templates/download_files.yml
                  parameters:
                    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
                - task: PowerShell@2
                  displayName: Set-up processing folder
                  inputs:
                    targetType: inline
                    script: |
                      New-Item -ItemType Directory -Force -Path $env:ProcessingPath
                      Add-MpPreference -ExclusionProcess c:\dev\agent
                      Add-MpPreference -ExclusionProcess Manipula.exe
                      Add-MpPreference -ExclusionProcess InstrumentBuilder.exe
                - task: PowerShell@2
                  displayName: Run data delivery
                  inputs:
                    filePath: $(Agent.BuildDirectory)/s/scripts/DeliverData.ps1
                    pwsh: true
                - task: PowerShell@2
                  displayName: Clean-up processing folder
                  inputs:
                    targetType: inline
                    script: |-
                      Remove-Item -Recurse -Force $env:ProcessingPath
                      Remove-MpPreference -ExclusionProcess c:\dev\agent
                      Remove-MpPreference -ExclusionProcess Manipula.exe
                      Remove-MpPreference -ExclusionProcess InstrumentBuilder.exe