parameters:
  - name : VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger:
- none

pr:
- none

variables:
  - group: ${{ parameters.VarGroup }}
  - name: ServerParkName
    value: gusty
  - name: SurveyType
    value: LM
  - name: PackageExtension
    value: zip
  - name: TempPath
    value: c:\blaise\temp\datadelivery\lm

stages:
 - stage: DataDelivery
   displayName: Lms Data Delivery
   jobs:
    - deployment: LmsDeliveryData
      timeoutInMinutes: 0
      environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: data-delivery
      strategy:
        runOnce:
          deploy: 
           steps:
               - checkout: self

               - task: DownloadSecureFile@1
                 displayName: 'Download GCP Key'
                 name: gcpkey
                 inputs:
                      secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'
          
               - task: DownloadSecureFile@1
                 displayName: 'Download blaise registry file'
                 name: BlaiseRegistrySettings
                 inputs:
                  secureFile: blaise.reg

               - powershell: |
                  regedit /i /s $(BlaiseRegistrySettings.secureFilePath)	
                 displayName: 'Register Blaise License'

               - task: PowerShell@2
                 displayName: Download Manipula Package
                 inputs:
                   targetType: 'inline'
                   script: |
                    Write-Host "Login to GCP"
                        gcloud auth activate-service-account $env:ENV_SHARED_SERVICE_ACCOUNT --key-file=$(gcpkey.secureFilePath)
                        
                        Write-Host "Downloading instrument"
                        gsutil cp gs://$env:ENV_SHARED_BUCKET/Manipula_Package_5_9_3.zip $env:TempPath\Manipula.zip

                        Write-Host "Downloading 7zip cli"
                        gsutil cp gs://ons-blaise-v2-europe-west2-shared-data/7za.exe $env:TempPath\7za.exe

                        Write-Host "GCP Login with compute service account"
                        gcloud auth login $env:ENV_VM_SERVICEACCOUNT

               - task: PowerShell@2
                 displayName: Create temp folders
                 inputs:
                  targetType: 'inline'
                  script: |
                    New-Item -ItemType Directory -Force -Path $env:TempPath
                    Add-MpPreference -ExclusionProcess c:\dev\agent
                    Add-MpPreference -ExclusionProcess Manipula.exe
                    Add-MpPreference -ExclusionProcess InstrumentBuilder.exe

               - task: PowerShell@2
                 displayName: Deliver LMS Instruments
                 inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/lms/DeliverLmsInstruments.ps1'
                  pwsh: true

               - task: PowerShell@2
                 displayName: Clean up temp folders
                 inputs:
                   targetType: 'inline'
                   script: |
                    Remove-Item -Recurse -Force $env:TempPath
                    Remove-MpPreference -ExclusionProcess c:\dev\agent
                    Remove-MpPreference -ExclusionProcess Manipula.exe
                    Remove-MpPreference -ExclusionProcess InstrumentBuilder.exe

