[tool.poetry]
name = "blaise-data-delivery-functions"
version = "0.1.0"
description = "A GCP Cloud Function to copy files from sandbox bucket to dev bucket"
authors = ["Sidra <sidra.javed@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
google-cloud = "^0.34.0"
google-cloud-storage = "^1.40.0"
setuptools = "^75.6.0"
google-cloud-logging = "^3.11.3"
parameterized = "^0.9.0"
