[tool.poetry]
name = "sandbox-data-delivery"
version = "0.1.0"
description = "GCP Cloud Function to copy files from sandbox NiFi bucket to dev NiFi bucket"
authors = ["Blaise Team"]

[tool.poetry.dependencies]
python = "^3.9"
google-cloud-storage = "^1.40.0"
google-cloud-logging = "^3.11.3"
parameterized = "^0.9.0"
