name: Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, preprod, prod ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run unittest
        run: poetry run python -m unittest discover cloud_functions
