name: Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, preprod, prod ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        working-directory: cloud_functions
        run: poetry install
      - name: Run unittest
        working-directory: cloud_functions
        run: poetry run python -m unittest
